# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: 'Soumilajmera'  # env variable name for username
        server-password: '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'


        settings-path: settings.xml



    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B deploy --file pom.xml -s /home/ec2-user/.m2/settings.xml
      env:
        GITHUB_TOKEN: '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'
